# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
source 'https://github.com/CocoaPods/Specs.git'

target 'ReadingEnglish' do
   pod 'HTMLKit', '~> 0.9.2'
   pod 'MBProgressHUD', '~> 0.9.2'
   pod 'KxMenu', '~> 1'
   pod 'UPStackMenu', '~> 1.0.0'
   pod 'Firebase/Core'
   pod 'Firebase/AdMob'
   pod 'TesseractOCRiOS', '~> 4.0.0'
   pod 'Kiwi', '~> 2.3.1'

  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for SmartEdict

end
